name: Build for Apple Silicon Macs

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Apple Silicon native and notarized dmg file
    runs-on: macos-14


    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Meson
        run: |
          python -m pip install --upgrade pip setuptools
          pip install meson

      - name: Install dependencies and configure environment
        run: |
          export HOMEBREW_NO_INSTALL_CLEANUP=1
          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
          export LDFLAGS="-L/opt/homebrew/opt/icu4c/lib -L/opt/homebrew/opt/libiconv/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/icu4c/include -I/opt/homebrew/include -I/opt/homebrew/opt/libiconv/include"
          export PKG_CONFIG_PATH="/opt/homebrew/opt/icu4c/lib/pkgconfig:/opt/homebrew/opt/openal-soft/lib/pkgconfig"
          # Skip brew update for now, see https://github.com/actions/setup-python/issues/577
          # brew update
          brew install boost ffmpeg ffms2 fftw \
          hunspell libass libiconv luarocks \
          meson ninja openal-soft portaudio \
          pulseaudio uchardet wxwidgets zlib
          luarocks install luafilesystem 1.8.0
          luarocks install moonscript --dev

      - name: Configure
        run: meson build_static -Ddefault_library=static -Dbuildtype=debugoptimized -Dbuild_osx_bundle=true -Dlocal_boost=true

      - name: Build
        run: meson compile -C build_static
        
      # Skipped because of test failure
      # - name: Run test
      #   run: meson test -C build_static --verbose

      # macOS artifacts
      - name: Generate macOS bundle
        run: meson compile osx-bundle -C build_static

      - name: Sign the app bundle
        run: codesign --sign - --force --deep build_static/Aegisub.app

      - name: Generate macOS app dmg
        run: meson compile osx-build-dmg -C build_static

      - name: Upload artifacts - macOS dmg
        uses: actions/upload-artifact@v4
        with:
          name: Aegisub-3.4.1-darwin-aarch64
          path: build_static/Aegisub-3.4.1.dmg
          if-no-files-found: error
