name: Build for Apple Silicon Macs

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Apple Silicon native and notarized dmg file
    runs-on: macos-latest


    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Meson
        run: |
          python -m pip install --upgrade pip setuptools
          pip install meson

      - name: Install dependencies and configure environment
        run: |
          export HOMEBREW_NO_INSTALL_CLEANUP=1
          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
          export LDFLAGS="-L/opt/homebrew/opt/icu4c/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/icu4c/include -I/opt/homebrew/include"
          export PKG_CONFIG_PATH="/opt/homebrew/opt/icu4c/lib/pkgconfig"
          # Skip brew update for now, see https://github.com/actions/setup-python/issues/577
          # brew update
          brew install cmake ninja pkg-config libass boost zlib ffms2 fftw hunspell luarocks pulseaudio ffmpeg boost wxwidgets icu4c
          # these steps are skipped because of the permission issue
          # luarocks install luafilesystem 1.8.0
          # luarocks install moonscript --dev

      - name: Configure
        run: meson build_static -Ddefault_library=static -Dbuildtype=debugoptimized -Dbuild_osx_bundle=true -Dlocal_boost=true

      - name: Build
        run: meson compile -C build_static

#      These steps are temporarily skipped due to the test failure
#      - name: Run test
#        run: meson test -C build --verbose "gtest main"

      # macOS artifacts
      - name: Generate macOS installer
        run: |
          meson compile osx-bundle -C build_static
          meson compile osx-build-dmg -C build_static

      - name: Upload artifacts - macOS dmg
        uses: actions/upload-artifact@v3
        with:
          name: Apple Silicon native - installer
          path: build_static/Aegisub-*.dmg
          if-no-files-found: error
